stages:
  - build
  - deploy

variables:
  NODE_ENV: production
  CACHE_KEY: ${CI_COMMIT_REF_SLUG}

cache:
  key: ${CACHE_KEY}
  paths:
    - node_modules/

build:
  stage: build
  tags:
    - node
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 1h
  only:
    - main

deploy:
  stage: deploy
  tags:
    - node
  dependencies:
    - build
  script:
    - ssh -o StrictHostKeyChecking=no web@192.168.110.3 "
        cd /home/rzidinc/Projects/sites/wcd_cakrawala_4 &&
        rm -rf dist &&
        mkdir dist"
    - scp -r dist/* web@192.168.110.3:/home/rzidinc/Projects/sites/wcd_cakrawala_4/dist
  only:
    - main
