stages:
  - sync
  - build
  - deploy

variables:
  NODE_ENV: production

sync:
  stage: sync
  script:
    - echo "Syncing repository from GitHub..."
    - git config --global user.name "GitHub Mirror"
    - git config --global user.email "github-mirror@example.com"
    - git remote add github https://$GITHUB_TOKEN@github.com/RZID/PersonalWeb.git || true
    - git fetch github
    - git reset --hard github/main
  only:
    - triggers

build:
  stage: build
  script:
    - echo "Installing dependencies..."
    - yarn install
    - echo "Building project..."
    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 1h
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying to server..."
    - ssh -o StrictHostKeyChecking=no web@192.168.110.3 "
        cd /home/rzidinc/Projects/sites/wcd_cakrawala_4 &&
        rm -rf dist &&
        mkdir dist"
    - scp -r dist/* web@192.168.110.3:/home/rzidinc/Projects/sites/wcd_cakrawala_4/dist
  only:
    - main
