name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab pipeline
      - run: |
          curl -X POST \
            "https://gitlab.rzidinc.com/api/v4/projects/1/trigger/pipeline?token=${GITLAB_TOKEN}&ref=main"
