name: Trigger GitLab CI

on:
  push:
    branches:
      - main

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab pipeline
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
        run: |
          curl -X POST \
            -F token=$GITLAB_TOKEN \
            -F ref=main \
            https://gitlab.rzidinc.com/api/v4/projects/2/trigger/pipeline
